import type { CardId } from '@/engine/types';

/**
 * Perguntas do jogo, baseadas na apresentação "Fábrica de software" (introdução ao desenvolvimento de soluções
 * tecnológicas para o ensino médio): software, programação, linguagens (Python, Java, PHP), frameworks, bibliotecas,
 * sites no-code, jogos e filmes sobre programação.
 *
 * Cada carta puxa um tema da apresentação (`TOPIC_BY_CARD`). A primeira carta jogada decide a pergunta; mãos grandes
 * (4–5 cartas) puxam as mais difíceis. Errar não trava nada: cada resposta errada só tira precisão da mão.
 */
export interface Question {
  id: string;
  /** Carta que puxa a pergunta: ela vale o dobro quando lidera a mão. */
  card: CardId;
  /** Tema da apresentação, mostrado ao jogador. */
  topic: string;
  hard: boolean;
  /** Use `código` entre crases para destacar trechos. */
  prompt: string;
  /** Trecho opcional mostrado junto da pergunta. */
  code?: string;
  options: string[];
  /** Posição da resposta certa em `options`. */
  answer: number;
  /** Mostrada depois de acertar: é aqui que o jogador aprende. */
  explanation: string;
}

export const TOPIC_BY_CARD: Record<CardId, string> = {
  variable: 'O que é software',
  operator: 'Tipos de software',
  boolean: 'O que é programação',
  condition: 'Para que serve programar',
  for: 'Programação no dia a dia',
  while: 'Python',
  list: 'Java',
  dictionary: 'PHP',
  set: 'Escolhendo a linguagem',
  function: 'Bibliotecas',
  parameter: 'Como usar bibliotecas',
  return: 'Frameworks',
  recursion: 'Sites no-code',
  search: 'Programação e jogos',
  'unit-test': 'O Jogo da Imitação',
  breakpoint: 'Estrelas Além do Tempo',
};

/**
 * Gira as alternativas para que a certa não fique sempre na mesma posição. É determinístico (depende só do id),
 * então a pergunta é a mesma em qualquer navegador e nos saves.
 */
function spread(question: Question): Question {
  const n = question.options.length;
  const target = [...question.id].reduce((sum, ch) => sum + ch.charCodeAt(0), 0) % n;
  const shift = (target - question.answer + n) % n;
  const options = question.options.map((_, i, all) => all[(i - shift + n) % n] as string);
  return { ...question, options, answer: target };
}

const q = (
  id: string,
  card: CardId,
  hard: boolean,
  prompt: string,
  options: string[],
  answer: number,
  explanation: string,
  code?: string,
): Question =>
  spread({
    id,
    card,
    topic: TOPIC_BY_CARD[card],
    hard,
    prompt,
    code,
    options,
    answer,
    explanation,
  });

export const QUESTIONS: readonly Question[] = [
  // ------------------------------------------------------------ O que é software
  q(
    'q-variable-1',
    'variable',
    false,
    'O que é um software?',
    [
      'A parte física do computador, como a tela e o teclado',
      'A parte lógica: programas e instruções que orientam o hardware',
      'Um tipo de cabo de internet',
      'Somente os jogos instalados no celular',
    ],
    1,
    'Software é a parte lógica dos dispositivos: programas e instruções que dizem ao hardware o que fazer.',
  ),
  q(
    'q-variable-2',
    'variable',
    false,
    'O que o software orienta o hardware a fazer?',
    [
      'Nada: o hardware funciona sozinho',
      'Tarefas, como rodar aplicativos, abrir sites e gerenciar dados',
      'Só ligar e desligar a tomada',
      'Somente imprimir documentos',
    ],
    1,
    'É o software que manda o hardware rodar aplicativos, abrir sites e gerenciar dados.',
  ),
  q(
    'q-variable-3',
    'variable',
    true,
    'Um celular tem tela, bateria, câmera, Android e o aplicativo do WhatsApp. Quais destes itens são software?',
    ['Tela, bateria e câmera', 'Android e WhatsApp', 'Bateria e Android', 'Todos os cinco'],
    1,
    'Tela, bateria e câmera são hardware (físicos). O Android (sistema operacional) e o WhatsApp (aplicativo) são software.',
  ),

  // ------------------------------------------------------------ Tipos de software
  q(
    'q-operator-1',
    'operator',
    false,
    'Windows, Android e iOS são exemplos de qual tipo de software?',
    ['Navegadores', 'Sistemas operacionais', 'Produtividade', 'Jogos'],
    1,
    'Windows, Android e iOS são sistemas operacionais: eles controlam o aparelho e rodam os outros programas.',
  ),
  q(
    'q-operator-2',
    'operator',
    false,
    'Google Chrome, Safari e Firefox são exemplos de…',
    ['Navegadores', 'Sistemas operacionais', 'Planilhas', 'Redes sociais'],
    0,
    'Navegadores são os softwares que usamos para abrir e visitar sites.',
  ),
  q(
    'q-operator-3',
    'operator',
    true,
    'Word, Google Sheets e Canva ajudam a escrever, calcular e criar designs. Qual é a categoria deles?',
    ['Sistemas operacionais', 'Navegadores', 'Streaming', 'Produtividade'],
    3,
    'Programas de produtividade existem para resolver tarefas do dia a dia: textos, tabelas, apresentações e designs.',
  ),

  // ------------------------------------------------------------ O que é programação
  q(
    'q-boolean-1',
    'boolean',
    false,
    'O que é programação?',
    [
      'Assistir vídeos sobre tecnologia',
      'Escrever instruções organizadas numa linguagem que o computador entende',
      'Montar as peças físicas de um computador',
      'Navegar rápido na internet',
    ],
    1,
    'Programar é escrever um conjunto de instruções organizadas, numa linguagem que o computador entende.',
  ),
  q(
    'q-boolean-2',
    'boolean',
    false,
    'A programação funciona como uma…',
    ['Receita de bolo', 'Pintura em tela', 'Música de fundo', 'Fotografia'],
    0,
    'Como numa receita, você passa os passos na ordem certa e o dispositivo executa exatamente o que foi escrito.',
  ),
  q(
    'q-boolean-3',
    'boolean',
    true,
    'Na comparação com uma receita de bolo, quem seria o "cozinheiro" que segue as instruções?',
    [
      'O programador, que lê o código pronto',
      'O computador, que executa as instruções escritas',
      'O usuário, que só olha a tela',
      'A internet, que entrega os ingredientes',
    ],
    1,
    'O programador escreve a receita (o código) e o computador é quem a executa, passo a passo.',
  ),

  // ------------------------------------------------------------ Para que serve programar
  q(
    'q-condition-1',
    'condition',
    false,
    'Para que serve a programação?',
    [
      'Só para jogar videogame',
      'Para criar sistemas, aplicativos, sites, jogos e ferramentas',
      'Apenas para consertar impressoras',
      'Não serve para nada no dia a dia',
    ],
    1,
    'Com programação criamos sistemas, aplicativos, sites, jogos e ferramentas.',
  ),
  q(
    'q-condition-2',
    'condition',
    false,
    'Além de criar coisas novas, programar também ajuda a…',
    [
      'Automatizar tarefas e resolver problemas',
      'Aumentar o brilho da tela',
      'Deixar a internet mais barata',
      'Evitar o uso de eletricidade',
    ],
    0,
    'A programação serve para criar ferramentas que automatizam tarefas ou solucionam problemas.',
  ),
  q(
    'q-condition-3',
    'condition',
    true,
    'Um software não é criado só "para ser um programa". Normalmente ele nasce para…',
    [
      'Ocupar espaço no celular',
      'Resolver um problema ou atender a uma necessidade',
      'Substituir o hardware',
      'Enfeitar a tela do computador',
    ],
    1,
    'Todo bom software parte de um problema real ou de uma necessidade das pessoas.',
  ),

  // ------------------------------------------------------------ Programação no dia a dia
  q(
    'q-for-1',
    'for',
    false,
    'WhatsApp, Instagram, TikTok e YouTube são exemplos de…',
    ['Redes sociais', 'Sistemas operacionais', 'Linguagens de programação', 'Hardware'],
    0,
    'Todas essas redes sociais são feitas com programação.',
  ),
  q(
    'q-for-2',
    'for',
    false,
    'Netflix e Spotify, que entregam filmes e músicas pela internet, são exemplos de…',
    ['Navegadores', 'Planilhas', 'Streaming', 'Sistemas operacionais'],
    2,
    'Serviços de streaming transmitem conteúdo pela internet, e por trás deles há muito código.',
  ),
  q(
    'q-for-3',
    'for',
    true,
    'Quando você pesquisa algo no Google Search usando o Chrome, qual é a melhor descrição?',
    [
      'Nenhum código está envolvido',
      'Dois softwares feitos com programação: o navegador e o buscador',
      'Só hardware está trabalhando',
      'É um filme em streaming',
    ],
    1,
    'O Chrome (navegador) e o Google Search (busca) são softwares criados por programadores.',
  ),

  // ------------------------------------------------------------ Python
  q(
    'q-while-1',
    'while',
    false,
    'Na apresentação, o Python é comparado a…',
    [
      'Um canivete suíço',
      'O esqueleto de um prédio',
      'A fiação elétrica de uma casa',
      'Um martelo',
    ],
    0,
    'Python é como uma ferramenta universal: simples e direta, serve para muita coisa.',
  ),
  q(
    'q-while-2',
    'while',
    false,
    'Qual é uma característica do Python?',
    [
      'Ser muito rígida e complicada',
      'Ser simples e versátil',
      'Só servir para criar sites',
      'Só funcionar em videogames',
    ],
    1,
    'A força do Python é a simplicidade e a versatilidade.',
  ),
  q(
    'q-while-3',
    'while',
    true,
    'O que dá para construir com Python, segundo a apresentação?',
    [
      'Só planilhas',
      'Desde automações rápidas até inteligência artificial complexa',
      'Apenas sistemas operacionais',
      'Só sites de venda online',
    ],
    1,
    'Python vai de pequenas automações até inteligência artificial, sem complicações.',
  ),

  // ------------------------------------------------------------ Java
  q(
    'q-list-1',
    'list',
    false,
    'O Java é comparado a…',
    [
      'Um canivete suíço',
      'O esqueleto e a fundação de um prédio de vários andares',
      'A canalização de uma casa',
      'Uma receita de bolo',
    ],
    1,
    'Java é como a estrutura de um prédio: organizada e firme.',
  ),
  q(
    'q-list-2',
    'list',
    false,
    'Quais palavras descrevem o Java?',
    ['Simples e solta', 'Organizada, rígida e segura', 'Visual e sem código', 'Lenta e inútil'],
    1,
    'Java é organizada, rígida e segura, ótima para sistemas grandes.',
  ),
  q(
    'q-list-3',
    'list',
    true,
    'Por que o Java é uma boa escolha para grandes sistemas e aplicações empresariais?',
    [
      'Porque ela não precisa de computador',
      'Porque garante que sistemas grandes funcionem sem falhar',
      'Porque foi criada só para fazer sites',
      'Porque é a única linguagem que existe',
    ],
    1,
    'A estrutura rígida e segura do Java ajuda grandes sistemas a funcionarem sem falhar.',
  ),

  // ------------------------------------------------------------ PHP
  q(
    'q-dictionary-1',
    'dictionary',
    false,
    'O PHP é descrito como o…',
    ['Motor da Web', 'Canivete suíço', 'Esqueleto do prédio', 'Cozinheiro da receita'],
    0,
    'O PHP é o motor da web: foi criado para fazer sites funcionarem no servidor.',
  ),
  q(
    'q-dictionary-2',
    'dictionary',
    false,
    'O PHP foi criado especificamente para…',
    [
      'Fazer sites funcionarem no servidor',
      'Criar jogos de computador',
      'Controlar robôs',
      'Editar vídeos',
    ],
    0,
    'O PHP roda no servidor e faz os sites funcionarem.',
  ),
  q(
    'q-dictionary-3',
    'dictionary',
    true,
    'O PHP é como a canalização e a fiação elétrica de uma casa. O que ele liga?',
    [
      'O usuário às bases de dados, de forma ágil e direta',
      'O teclado ao mouse',
      'A bateria à tela',
      'O Wi-Fi à geladeira',
    ],
    0,
    'Assim como a fiação leva energia, o PHP conecta o usuário às bases de dados.',
  ),

  // ------------------------------------------------------------ Escolhendo a linguagem
  q(
    'q-set-1',
    'set',
    false,
    'Para uma automação rápida ou um projeto de inteligência artificial, qual linguagem da apresentação combina mais?',
    ['Python', 'Java', 'PHP', 'Nenhuma'],
    0,
    'Python é simples e versátil: boa para automações e IA.',
  ),
  q(
    'q-set-2',
    'set',
    false,
    'Para um site que precisa conversar com um banco de dados no servidor, a escolha mais natural é…',
    ['Java', 'PHP', 'Planilha', 'Sistema operacional'],
    1,
    'O PHP nasceu para fazer sites funcionarem no servidor e acessar bases de dados.',
  ),
  q(
    'q-set-3',
    'set',
    true,
    'Ligue cada linguagem à sua analogia: Python, Java e PHP.',
    [
      'Python = esqueleto do prédio; Java = canivete suíço; PHP = motor da web',
      'Python = canivete suíço; Java = esqueleto do prédio; PHP = canalização e fiação',
      'Python = fiação; Java = canivete suíço; PHP = receita de bolo',
      'Python = receita de bolo; Java = fiação; PHP = esqueleto do prédio',
    ],
    1,
    'Python é o canivete suíço, Java é a fundação do prédio e PHP é a canalização e fiação ligadas à casa.',
  ),

  // ------------------------------------------------------------ Bibliotecas
  q(
    'q-function-1',
    'function',
    false,
    'O que é uma biblioteca (library) na programação?',
    [
      'Um lugar com livros de papel',
      'Uma coleção de códigos prontos que você pode "pegar emprestado"',
      'Um tipo de computador',
      'Um site sem código',
    ],
    1,
    'Biblioteca é uma coleção de códigos prontos que resolvem um problema específico.',
  ),
  q(
    'q-function-2',
    'function',
    false,
    'Para que usamos bibliotecas?',
    [
      'Para reinventar a roda a cada projeto',
      'Para resolver um problema sem precisar reescrever tudo',
      'Para apagar o código pronto',
      'Para desligar o computador',
    ],
    1,
    'Elas evitam "reinventar a roda": você usa o que já foi feito e testado.',
  ),
  q(
    'q-function-3',
    'function',
    true,
    'Qual destes é um bom exemplo de tarefa que uma biblioteca resolve?',
    [
      'Calcular datas, criar um gráfico ou animar um botão',
      'Construir um computador inteiro',
      'Instalar um sistema operacional',
      'Trocar a bateria do celular',
    ],
    0,
    'Cada biblioteca tem foco único: datas, gráficos, animações e assim por diante.',
  ),

  // ------------------------------------------------------------ Como usar bibliotecas
  q(
    'q-parameter-1',
    'parameter',
    false,
    'Numa biblioteca, quem decide quando e como usá-la?',
    [
      'A própria biblioteca',
      'O seu código: você está no controle',
      'O sistema operacional',
      'O usuário final',
    ],
    1,
    'Você chama a biblioteca quando e como quiser: o controle é do seu código.',
  ),
  q(
    'q-parameter-2',
    'parameter',
    false,
    'Uma biblioteca costuma ter foco único. Isso quer dizer que ela…',
    [
      'Resolve uma tarefa ou um conjunto bem pequeno de tarefas',
      'Faz tudo no projeto sozinha',
      'Só funciona uma vez',
      'Só existe para jogos',
    ],
    0,
    'Foco único: ela é boa em uma coisa específica.',
  ),
  q(
    'q-parameter-3',
    'parameter',
    true,
    'Por que se diz que uma biblioteca é "leve e flexível"?',
    [
      'Porque pesa poucos gramas',
      'Porque dá para colocar e tirar do projeto sem quebrar a estrutura inteira',
      'Porque só funciona no celular',
      'Porque não precisa de código',
    ],
    1,
    'Como é uma peça independente, você a adiciona ou remove com facilidade.',
  ),

  // ------------------------------------------------------------ Frameworks
  q(
    'q-return-1',
    'return',
    false,
    'Um framework é uma estrutura pronta que…',
    [
      'Organiza o projeto e dá a base para você construir em cima',
      'Só serve para jogos',
      'Apaga o seu código',
      'Substitui o computador',
    ],
    0,
    'Framework é uma estrutura base: ele define como o projeto se organiza e você completa o resto.',
  ),
  q(
    'q-return-2',
    'return',
    false,
    'Qual é a diferença de espírito entre biblioteca e framework?',
    [
      'Nenhuma, são a mesma coisa',
      'Na biblioteca você chama o código; no framework a estrutura guia o seu código',
      'Biblioteca é hardware e framework é software',
      'Framework só existe em Python',
    ],
    1,
    'Com a biblioteca o controle é seu. Com o framework, ele impõe a estrutura e chama o seu código.',
  ),
  q(
    'q-return-3',
    'return',
    true,
    'Você precisa só de uma tarefa pequena, como gerar um gráfico. O que combina melhor?',
    [
      'Uma biblioteca',
      'Um framework completo',
      'Um novo sistema operacional',
      'Um novo computador',
    ],
    0,
    'Para uma tarefa pequena e específica, a biblioteca (leve e flexível) é a escolha certa.',
  ),

  // ------------------------------------------------------------ Sites no-code
  q(
    'q-recursion-1',
    'recursion',
    false,
    'O que são sites no-code?',
    [
      'Sites criados por ferramentas visuais, sem digitar código',
      'Sites que não funcionam',
      'Sites que só têm texto',
      'Sites escritos só em Python',
    ],
    0,
    'No-code significa "sem código": você monta o site com ferramentas visuais.',
  ),
  q(
    'q-recursion-2',
    'recursion',
    false,
    'Qual destas linguagens você NÃO precisa digitar num site no-code?',
    ['HTML, CSS e JavaScript', 'Português', 'Inglês', 'Emojis'],
    0,
    'As ferramentas no-code eliminam a necessidade de digitar HTML, CSS ou JavaScript.',
  ),
  q(
    'q-recursion-3',
    'recursion',
    true,
    'Quais coisas podem ser criadas com ferramentas no-code?',
    [
      'Só planilhas',
      'Páginas da web, lojas virtuais e sistemas',
      'Apenas hardware',
      'Somente filmes',
    ],
    1,
    'Com no-code dá para criar páginas da web, lojas virtuais e sistemas inteiros.',
  ),

  // ------------------------------------------------------------ Programação e jogos
  q(
    'q-search-1',
    'search',
    false,
    '"The Farmer Was Replaced" é um jogo baseado em qual linguagem?',
    ['Python', 'PHP', 'Java', 'Assembly'],
    0,
    'Nesse jogo você aprende a automatizar tarefas usando uma linguagem baseada em Python.',
  ),
  q(
    'q-search-2',
    'search',
    false,
    '"Shenzhen I/O" usa qual tipo de linguagem?',
    ['Python', 'Assembly customizado', 'PHP', 'HTML'],
    1,
    'Shenzhen I/O ensina programação com um Assembly customizado, bem perto da máquina.',
  ),
  q(
    'q-search-3',
    'search',
    true,
    'Os dois jogos da apresentação, "The Farmer Was Replaced" e "Shenzhen I/O", têm em comum…',
    [
      'Só rodam em celulares',
      'Usam programação como parte do jogo e estão disponíveis em computadores',
      'Não têm código',
      'São filmes na Netflix',
    ],
    1,
    'Ambos usam programação como mecânica de jogo e estão disponíveis em computadores.',
  ),

  // ------------------------------------------------------------ O Jogo da Imitação
  q(
    'q-unit-test-1',
    'unit-test',
    false,
    'O filme "O Jogo da Imitação" conta a história de qual matemático?',
    ['Alan Turing', 'Katherine Johnson', 'Dorothy Vaughan', 'Mary Jackson'],
    0,
    'O filme conta a história real de Alan Turing.',
  ),
  q(
    'q-unit-test-2',
    'unit-test',
    false,
    'Qual era a missão quase impossível de Alan Turing na Segunda Guerra Mundial?',
    [
      'Construir um foguete',
      'Decifrar a "Enigma", a máquina de códigos secretos',
      'Criar um videogame',
      'Fazer um site de buscas',
    ],
    1,
    'A missão era decifrar a Enigma, a máquina usada pelos inimigos.',
  ),
  q(
    'q-unit-test-3',
    'unit-test',
    true,
    'Por que decifrar a Enigma era tão difícil?',
    [
      'Porque ela só funcionava de dia',
      'Porque as senhas mudavam todas as noites à meia-noite',
      'Porque ela não tinha código algum',
      'Porque era uma máquina de lavar',
    ],
    1,
    'As senhas mudavam todas as noites à meia-noite, o que tornava a tarefa quase impossível.',
  ),

  // ------------------------------------------------------------ Estrelas Além do Tempo
  q(
    'q-breakpoint-1',
    'breakpoint',
    false,
    'Quais são as três mulheres do filme "Estrelas Além do Tempo"?',
    [
      'Katherine Johnson, Dorothy Vaughan e Mary Jackson',
      'Ada Lovelace, Marie Curie e Rosa Parks',
      'Alan Turing, Katherine Johnson e Mary Jackson',
      'Dorothy Vaughan, Marie Curie e Ada Lovelace',
    ],
    0,
    'O filme conta a história real de Katherine Johnson, Dorothy Vaughan e Mary Jackson.',
  ),
  q(
    'q-breakpoint-2',
    'breakpoint',
    false,
    'Segundo a apresentação, como essas três mulheres mudaram o mundo?',
    [
      'Com a mente e a matemática',
      'Com super-poderes de verdade',
      'Com capas e máscaras',
      'Só com sorte',
    ],
    0,
    'Elas mudaram o mundo com a mente e a matemática, sem capas.',
  ),
  q(
    'q-breakpoint-3',
    'breakpoint',
    true,
    'Onde estão disponíveis os dois filmes da apresentação?',
    [
      'Os dois na Netflix',
      '"O Jogo da Imitação" na Netflix e "Estrelas Além do Tempo" no Disney+',
      '"O Jogo da Imitação" no Disney+ e "Estrelas Além do Tempo" na Netflix',
      'Os dois só no cinema',
    ],
    1,
    '"O Jogo da Imitação" está na Netflix e "Estrelas Além do Tempo" no Disney+.',
  ),

  // ------------------------------------------------------------ Mais perguntas (variedade)
  // O que é software
  q(
    'q-variable-4',
    'variable',
    false,
    'Qual destes é um exemplo de hardware?',
    ['O sistema Android', 'O teclado', 'O aplicativo Spotify', 'O navegador Chrome'],
    1,
    'Teclado, mouse e tela são hardware: a parte física que dá para tocar.',
  ),
  q(
    'q-variable-5',
    'variable',
    false,
    'O que acontece com um computador sem nenhum software?',
    [
      'Fica mais rápido',
      'Tem as peças físicas, mas não sabe o que fazer',
      'Vira um celular',
      'Funciona melhor',
    ],
    1,
    'Sem software, o hardware não recebe instruções: ele existe, mas não tem o que executar.',
  ),
  q(
    'q-variable-6',
    'variable',
    false,
    'Qual frase descreve a relação entre hardware e software?',
    [
      'O hardware é a parte física e o software diz a ele o que fazer',
      'O software é a parte física e o hardware é a lógica',
      'Os dois são exatamente a mesma coisa',
      'Só o hardware importa',
    ],
    0,
    'Hardware é o corpo; software são as instruções que mandam esse corpo trabalhar.',
  ),
  q(
    'q-variable-7',
    'variable',
    true,
    'Qual par mostra um hardware e um software, nessa ordem?',
    [
      'Windows e mouse',
      'Câmera do celular e aplicativo de fotos',
      'Spotify e Netflix',
      'Tela e bateria',
    ],
    1,
    'A câmera é uma peça física (hardware) e o aplicativo de fotos é software que a controla.',
  ),
  q(
    'q-variable-8',
    'variable',
    true,
    'Um jogo instalado num console só funciona porque…',
    [
      'O console é feito só de software',
      'Os jogos não têm instruções',
      'O software do jogo envia instruções ao hardware do console',
      'O jogo é uma peça física',
    ],
    2,
    'O jogo é software: ele diz ao hardware do console o que mostrar e como reagir.',
  ),
  // Tipos de software
  q(
    'q-operator-4',
    'operator',
    false,
    'O Microsoft Word é um exemplo de software de…',
    ['Sistema operacional', 'Produtividade', 'Navegador', 'Streaming'],
    1,
    'Word serve para escrever textos: é um software de produtividade.',
  ),
  q(
    'q-operator-5',
    'operator',
    false,
    'Qual destes é um navegador?',
    ['Windows', 'Excel', 'Firefox', 'Spotify'],
    2,
    'Firefox é um navegador, usado para visitar sites.',
  ),
  q(
    'q-operator-6',
    'operator',
    false,
    'Qual é a função de um sistema operacional?',
    [
      'Só tocar músicas',
      'Controlar o aparelho e permitir que os outros programas rodem',
      'Só abrir sites',
      'Imprimir documentos',
    ],
    1,
    'O sistema operacional gerencia o aparelho e é a base onde os outros programas funcionam.',
  ),
  q(
    'q-operator-7',
    'operator',
    true,
    'O Android roda num celular e, dentro dele, roda o Chrome. Qual é a relação entre os dois?',
    [
      'O Android roda dentro do Chrome',
      'O Chrome (navegador) roda sobre o Android (sistema operacional)',
      'São o mesmo software',
      'Funcionam totalmente separados',
    ],
    1,
    'O sistema operacional é a base; o navegador é um programa que roda sobre ela.',
  ),
  q(
    'q-operator-8',
    'operator',
    true,
    'Qual alternativa tem apenas softwares de produtividade?',
    [
      'Windows, Android e iOS',
      'Chrome, Safari e Firefox',
      'Netflix, Spotify e YouTube',
      'Word, Google Sheets e Canva',
    ],
    3,
    'Texto, planilha e design são tarefas do dia a dia: o território dos softwares de produtividade.',
  ),
  // O que é programação
  q(
    'q-boolean-4',
    'boolean',
    false,
    'Em programação, o que é o "código"?',
    [
      'Uma senha do Wi-Fi',
      'O conjunto de instruções escritas pelo programador',
      'Um tipo de cabo',
      'Um desenho na tela',
    ],
    1,
    'Código é o conjunto de instruções que o programador escreve para o computador executar.',
  ),
  q(
    'q-boolean-5',
    'boolean',
    false,
    'Quem escreve as instruções que o computador segue?',
    ['O programador', 'A tela', 'O teclado', 'O cabo de força'],
    0,
    'Quem programa escreve as instruções; o computador as executa.',
  ),
  q(
    'q-boolean-6',
    'boolean',
    false,
    'O computador executa as instruções…',
    [
      'Como foram escritas, passo a passo',
      'Do jeito que ele preferir',
      'Só as que acha importantes',
      'Sempre de trás para frente',
    ],
    0,
    'O computador não adivinha: ele segue exatamente o que foi escrito, na ordem.',
  ),
  q(
    'q-boolean-7',
    'boolean',
    true,
    'Numa receita, trocar a ordem dos passos pode estragar o bolo. Qual é o paralelo na programação?',
    [
      'A ordem das instruções muda o resultado',
      'A ordem nunca importa',
      'O computador reorganiza tudo sozinho',
      'Só o hardware é afetado',
    ],
    0,
    'A ordem das instruções importa: mudar a sequência pode mudar (ou quebrar) o resultado.',
  ),
  q(
    'q-boolean-8',
    'boolean',
    true,
    'Por que existem as linguagens de programação?',
    [
      'Para deixar o computador mais bonito',
      'Para que pessoas escrevam instruções que o computador consegue entender',
      'Para trocar peças do computador',
      'Para gastar menos energia',
    ],
    1,
    'Elas são a ponte entre o que a pessoa quer dizer e o que a máquina executa.',
  ),
  // Para que serve programar
  q(
    'q-condition-4',
    'condition',
    false,
    'Qual destes é algo criado com programação?',
    ['Uma cadeira de madeira', 'Um lápis', 'Um aplicativo de mensagens', 'Um copo de vidro'],
    2,
    'Aplicativos, sites e jogos nascem de código.',
  ),
  q(
    'q-condition-5',
    'condition',
    false,
    'Automatizar uma tarefa significa…',
    [
      'Fazer o computador repetir sozinho um trabalho que seria manual',
      'Deixar a tarefa mais lenta',
      'Apagar a tarefa',
      'Pedir a outra pessoa que faça',
    ],
    0,
    'Automatizar é programar o computador para fazer o trabalho repetitivo no nosso lugar.',
  ),
  q(
    'q-condition-6',
    'condition',
    false,
    'Programar ajuda a resolver problemas porque…',
    [
      'Elimina todos os problemas do mundo',
      'Só serve para fazer jogos',
      'Permite criar ferramentas sob medida para a necessidade',
      'Substitui o estudo',
    ],
    2,
    'Com programação dá para criar a ferramenta certa para cada problema.',
  ),
  q(
    'q-condition-7',
    'condition',
    true,
    'Uma escola quer avisar os pais quando um aluno falta. Como a programação ajuda?',
    [
      'Imprimindo mais folhas',
      'Criando um sistema que registra a falta e envia o aviso automaticamente',
      'Trocando o hardware',
      'Desligando o computador',
    ],
    1,
    'Um sistema pode registrar a falta e enviar o aviso sozinho, sem trabalho manual.',
  ),
  q(
    'q-condition-8',
    'condition',
    true,
    'Qual exemplo mostra a programação resolvendo um problema do dia a dia?',
    [
      'Um relógio de sol',
      'Uma pedra no caminho',
      'Um aplicativo de transporte que mostra o trajeto mais rápido',
      'Um mapa de papel esquecido em casa',
    ],
    2,
    'O app usa código para calcular rotas e resolver o problema de chegar mais rápido.',
  ),
  // Programação no dia a dia
  q(
    'q-for-4',
    'for',
    false,
    'YouTube e TikTok são exemplos de…',
    [
      'Hardware',
      'Plataformas de vídeo feitas com programação',
      'Sistemas operacionais',
      'Linguagens de programação',
    ],
    1,
    'Plataformas de vídeo são softwares enormes, feitos com programação.',
  ),
  q(
    'q-for-5',
    'for',
    false,
    'Qual destes serviços é de streaming de música?',
    ['Word', 'Chrome', 'Windows', 'Spotify'],
    3,
    'O Spotify entrega músicas pela internet: é um serviço de streaming.',
  ),
  q(
    'q-for-6',
    'for',
    false,
    'Quando você usa o aplicativo do seu banco no celular, existe programação envolvida?',
    [
      'Não, é tudo mágica',
      'Sim, o aplicativo foi criado por programadores',
      'Só o celular é programado',
      'Só em computadores',
    ],
    1,
    'Todo aplicativo é resultado de programação.',
  ),
  q(
    'q-for-7',
    'for',
    true,
    'Ao abrir um aplicativo no celular, quais softwares trabalham juntos?',
    [
      'Só o hardware',
      'O sistema operacional do celular e o aplicativo',
      'Só o aplicativo, o celular não precisa de software',
      'Apenas o navegador',
    ],
    1,
    'O sistema operacional roda o aparelho e o aplicativo roda sobre ele.',
  ),
  q(
    'q-for-8',
    'for',
    true,
    'Qual afirmação explica por que a programação está "em tudo"?',
    [
      'Só existe em empresas grandes',
      'Só os computadores de mesa têm programas',
      'Sites, apps, redes sociais, streaming e jogos dependem de código',
      'Só o hardware importa',
    ],
    2,
    'Quase tudo o que usamos digitalmente depende de software.',
  ),
  // Python
  q(
    'q-while-4',
    'while',
    false,
    'Qual linguagem a apresentação compara a um canivete suíço?',
    ['Java', 'PHP', 'Python', 'HTML'],
    2,
    'Python é versátil como um canivete suíço: serve para muita coisa.',
  ),
  q(
    'q-while-5',
    'while',
    false,
    'Python é conhecida por…',
    [
      'Ser impossível de aprender',
      'Ter uma sintaxe simples e legível',
      'Funcionar só no Windows',
      'Não ter bibliotecas',
    ],
    1,
    'A sintaxe simples e fácil de ler é uma das marcas do Python.',
  ),
  q(
    'q-while-6',
    'while',
    false,
    'O que dá para fazer com Python?',
    [
      'Automatizar tarefas e analisar dados',
      'Somente editar fotos',
      'Só montar hardware',
      'Nada além de uma calculadora',
    ],
    0,
    'Python é usado de automações simples a análise de dados e IA.',
  ),
  q(
    'q-while-7',
    'while',
    true,
    'Qual destas áreas usa muito o Python?',
    [
      'Só construção civil',
      'Inteligência artificial e ciência de dados',
      'Somente culinária',
      'Apenas desenho à mão',
    ],
    1,
    'Python é uma das linguagens mais usadas em IA e ciência de dados.',
  ),
  q(
    'q-while-8',
    'while',
    true,
    'Por que o Python é considerado bom para quem está começando?',
    [
      'O código é simples e fácil de ler',
      'Exige muitas regras rígidas',
      'Só tem uma função',
      'Não usa texto',
    ],
    0,
    'A simplicidade deixa o iniciante focar em pensar, e não em decorar regras complicadas.',
  ),
  // Java
  q(
    'q-list-4',
    'list',
    false,
    'Qual linguagem é descrita como "organizada, rígida e segura"?',
    ['Python', 'Java', 'PHP', 'Planilha'],
    1,
    'Java é organizada, rígida e segura.',
  ),
  q(
    'q-list-5',
    'list',
    false,
    'O Java é muito usado em…',
    [
      'Sistemas grandes e aplicações empresariais',
      'Só desenhos',
      'Apenas calculadoras de bolso',
      'Somente cartões de papel',
    ],
    0,
    'A solidez do Java o torna comum em sistemas grandes de empresas.',
  ),
  q(
    'q-list-6',
    'list',
    false,
    'Tradicionalmente, aplicativos de Android são escritos em…',
    ['Java', 'Excel', 'Word', 'Windows'],
    0,
    'Java (e hoje também Kotlin) é muito usado para apps de Android.',
  ),
  q(
    'q-list-7',
    'list',
    true,
    'Na analogia do prédio, o que o Java garante?',
    [
      'Que o prédio seja pequeno',
      'Que não haja regras',
      'Uma estrutura firme para sistemas grandes que não podem falhar',
      'Que o prédio seja decorado',
    ],
    2,
    'Como o esqueleto de um prédio, o Java dá uma base firme para sistemas grandes.',
  ),
  q(
    'q-list-8',
    'list',
    true,
    'O Java tem regras mais rígidas que o Python. Qual é a vantagem em sistemas grandes?',
    [
      'Elimina a necessidade de testar',
      'Faz o programa rodar sem computador',
      'Deixa o código sempre mais curto',
      'Ajuda a manter o código organizado e a evitar erros',
    ],
    3,
    'Regras rígidas mantêm projetos grandes organizados e previnem muitos erros.',
  ),
  // PHP
  q(
    'q-dictionary-4',
    'dictionary',
    false,
    'Onde o PHP roda?',
    ['Dentro da bateria', 'No servidor', 'No mouse', 'No cabo HDMI'],
    1,
    'O PHP roda no servidor, antes de a página chegar ao usuário.',
  ),
  q(
    'q-dictionary-5',
    'dictionary',
    false,
    'O PHP é muito usado para…',
    [
      'Editar vídeos',
      'Controlar robôs',
      'Fazer sites e sistemas web funcionarem',
      'Criar sistemas operacionais',
    ],
    2,
    'O PHP nasceu para fazer sites funcionarem.',
  ),
  q(
    'q-dictionary-6',
    'dictionary',
    false,
    'O WordPress, um dos sistemas de sites mais usados do mundo, é escrito em…',
    ['PHP', 'Assembly', 'Excel', 'Java'],
    0,
    'O WordPress é feito em PHP.',
  ),
  q(
    'q-dictionary-7',
    'dictionary',
    true,
    'O PHP liga o usuário às bases de dados. O que é uma base de dados?',
    [
      'Um lugar organizado onde as informações do site ficam guardadas',
      'Um tipo de cabo',
      'Uma tela',
      'Um jogo',
    ],
    0,
    'É onde ficam guardados usuários, produtos, mensagens e outras informações.',
  ),
  q(
    'q-dictionary-8',
    'dictionary',
    true,
    'Quando você faz login num site, a checagem de usuário e senha costuma acontecer…',
    ['No seu teclado', 'No servidor, por exemplo com PHP', 'No cabo de internet', 'Na sua tela'],
    1,
    'Essa verificação acontece no servidor, onde ficam os dados de verdade.',
  ),
  // Escolhendo a linguagem
  q(
    'q-set-4',
    'set',
    false,
    'Você quer um site que guarda dados de usuários no servidor. Qual linguagem da apresentação combina?',
    ['Windows', 'Chrome', 'PHP', 'Hardware'],
    2,
    'PHP é a linguagem do servidor e das bases de dados.',
  ),
  q(
    'q-set-5',
    'set',
    false,
    'Para um sistema enorme que não pode falhar, a escolha mais indicada é…',
    ['Java', 'Uma calculadora', 'Um navegador', 'Um teclado'],
    0,
    'Java é organizada, rígida e segura: ótima para sistemas grandes.',
  ),
  q(
    'q-set-6',
    'set',
    false,
    'Escolher uma linguagem de programação depende principalmente de…',
    [
      'A cor do computador',
      'O tamanho da tela',
      'Qual problema você quer resolver',
      'O preço do mouse',
    ],
    2,
    'Cada linguagem brilha em um tipo de problema: escolha a que combina com o seu.',
  ),
  q(
    'q-set-7',
    'set',
    true,
    'Uma startup quer testar rápido uma ideia de inteligência artificial. Qual linguagem combina?',
    ['Python', 'Assembly customizado', 'HTML puro', 'Excel'],
    0,
    'Python é simples, versátil e muito usada em IA.',
  ),
  q(
    'q-set-8',
    'set',
    true,
    'Qual pareamento está correto?',
    [
      'Java: sistemas grandes e seguros; PHP: sites no servidor',
      'Java: sites no servidor; PHP: sistemas grandes',
      'Python: só sites; PHP: só IA',
      'Java: só automações; Python: nada',
    ],
    0,
    'Java para sistemas grandes e seguros, PHP para sites no servidor e Python para o que for preciso, de automações a IA.',
  ),
  // Bibliotecas
  q(
    'q-function-4',
    'function',
    false,
    'Qual é uma vantagem de usar uma biblioteca?',
    [
      'Economizar tempo reaproveitando código pronto',
      'Deixar o código sempre mais lento',
      'Impedir o projeto de crescer',
      'Apagar bugs automaticamente',
    ],
    0,
    'Reaproveitar código pronto economiza tempo e esforço.',
  ),
  q(
    'q-function-5',
    'function',
    false,
    '"Reinventar a roda" em programação quer dizer…',
    [
      'Criar um jogo de corrida',
      'Refazer do zero algo que já existe pronto',
      'Trocar a bateria',
      'Consertar um carro',
    ],
    1,
    'É gastar tempo refazendo o que uma biblioteca já resolve.',
  ),
  q(
    'q-function-6',
    'function',
    false,
    'Qual destas é uma biblioteca de Python para gráficos?',
    ['Word', 'Chrome', 'Windows', 'Matplotlib'],
    3,
    'Matplotlib é uma biblioteca muito usada para criar gráficos em Python.',
  ),
  q(
    'q-function-7',
    'function',
    true,
    'Para analisar dados em tabelas com Python, uma biblioteca muito usada é…',
    ['Pandas', 'Photoshop', 'Netflix', 'Android'],
    0,
    'Pandas é uma biblioteca de Python feita para análise de dados.',
  ),
  q(
    'q-function-8',
    'function',
    true,
    'Usar uma biblioteca bem testada tende a…',
    [
      'Aumentar os erros',
      'Impedir qualquer teste',
      'Substituir o programador',
      'Reduzir erros, pois o código já foi usado por muita gente',
    ],
    3,
    'Código muito usado costuma ter seus erros já encontrados e corrigidos.',
  ),
  // Como usar bibliotecas
  q(
    'q-parameter-4',
    'parameter',
    false,
    'Para usar uma biblioteca no projeto, normalmente você precisa…',
    [
      'Comprar um novo computador',
      'Instalar ou importar a biblioteca no projeto',
      'Desinstalar o sistema operacional',
      'Escrever tudo de novo',
    ],
    1,
    'Você instala ou importa a biblioteca e passa a chamar o que ela oferece.',
  ),
  q(
    'q-parameter-5',
    'parameter',
    false,
    'Quem escolhe quais bibliotecas usar?',
    ['O teclado', 'O Wi-Fi', 'Ninguém', 'O programador, conforme a necessidade'],
    3,
    'É o programador que decide o que o projeto precisa.',
  ),
  q(
    'q-parameter-6',
    'parameter',
    false,
    'Se uma biblioteca deixar de ser necessária, você pode…',
    ['Quebrar o computador', 'Removê-la do projeto', 'Trocar o hardware', 'Nada, é impossível'],
    1,
    'Por serem peças independentes, bibliotecas podem ser retiradas com facilidade.',
  ),
  q(
    'q-parameter-7',
    'parameter',
    true,
    'Você só precisa de um calendário bonito num site. Qual abordagem combina?',
    [
      'Reescrever o site inteiro com um framework',
      'Trocar de linguagem',
      'Desistir do calendário',
      'Adicionar uma biblioteca de calendário e usar só o que precisa',
    ],
    3,
    'Para uma necessidade pequena e específica, uma biblioteca é a ferramenta certa.',
  ),
  q(
    'q-parameter-8',
    'parameter',
    true,
    'Por que uma biblioteca é considerada uma peça "independente"?',
    [
      'Porque nunca tem erros',
      'Porque funciona sem depender de uma estrutura imposta, e você a encaixa onde quiser',
      'Porque funciona sem código',
      'Porque só existe no hardware',
    ],
    1,
    'Ela não impõe a estrutura do projeto: o controle continua com o seu código.',
  ),
  // Frameworks
  q(
    'q-return-4',
    'return',
    false,
    'Django (Python) e Laravel (PHP) são exemplos de…',
    ['Frameworks', 'Sistemas operacionais', 'Navegadores', 'Redes sociais'],
    0,
    'Ambos são frameworks para criar sistemas web.',
  ),
  q(
    'q-return-5',
    'return',
    false,
    'O Spring é um framework de qual linguagem?',
    ['Excel', 'Java', 'HTML', 'Planilha'],
    1,
    'Spring é um dos frameworks mais usados em Java.',
  ),
  q(
    'q-return-6',
    'return',
    false,
    'Um framework ajuda a…',
    [
      'Desligar o computador',
      'Substituir o programador',
      'Esconder o código',
      'Organizar o projeto e acelerar o desenvolvimento com uma estrutura pronta',
    ],
    3,
    'O framework traz a base organizada e você completa o resto.',
  ),
  q(
    'q-return-7',
    'return',
    true,
    'No framework, "a estrutura chama o seu código". O que isso quer dizer?',
    [
      'A estrutura decide quando executar o que você escreveu',
      'Você chama o framework quando quiser',
      'Não existe código',
      'O framework é hardware',
    ],
    0,
    'No framework o controle é dele: você escreve as peças e ele decide quando usá-las.',
  ),
  q(
    'q-return-8',
    'return',
    true,
    'Qual situação pede mais um framework do que uma biblioteca?',
    [
      'Gerar um único gráfico',
      'Calcular uma data',
      'Animar um botão',
      'Montar um sistema web completo, com várias partes organizadas',
    ],
    3,
    'Para sistemas completos, a estrutura pronta do framework compensa.',
  ),
  // Sites no-code
  q(
    'q-recursion-4',
    'recursion',
    false,
    'Wix e Webflow são exemplos de…',
    [
      'Sistemas operacionais',
      'Linguagens de programação',
      'Ferramentas para criar sites sem programar',
      'Hardware',
    ],
    2,
    'São plataformas no-code: você monta o site de forma visual.',
  ),
  q(
    'q-recursion-5',
    'recursion',
    false,
    'Uma vantagem do no-code é…',
    [
      'Criar rápido sem saber programar',
      'Nunca poder alterar o site',
      'Exigir saber Java',
      'Só funcionar offline',
    ],
    0,
    'Quem não programa consegue colocar uma ideia no ar rapidamente.',
  ),
  q(
    'q-recursion-6',
    'recursion',
    false,
    'Num site no-code, você monta a página…',
    [
      'Digitando só em Assembly',
      'Arrastando e configurando blocos visuais',
      'Soldando placas',
      'Somente em papel',
    ],
    1,
    'As ferramentas no-code usam blocos visuais que você arrasta e configura.',
  ),
  q(
    'q-recursion-7',
    'recursion',
    true,
    'Qual é uma possível limitação do no-code?',
    [
      'Exige conhecer PHP',
      'Menos liberdade para personalizar tudo do que com código',
      'Não funciona na web',
      'Só vale para jogos',
    ],
    1,
    'Ferramentas prontas facilitam, mas limitam o que dá para personalizar.',
  ),
  q(
    'q-recursion-8',
    'recursion',
    true,
    'Alguém precisa lançar uma loja virtual simples em um dia, sem programador. O que combina?',
    [
      'Escrever tudo em Assembly',
      'Criar um framework próprio',
      'Esperar alguns meses',
      'Uma ferramenta no-code',
    ],
    3,
    'Para prazo curto e sem programador, o no-code é a escolha natural.',
  ),
  // Programação e jogos
  q(
    'q-search-4',
    'search',
    false,
    'Em "The Farmer Was Replaced", o jogador…',
    [
      'Só assiste vídeos',
      'Escreve código para automatizar a fazenda',
      'Só desenha',
      'Só digita senhas',
    ],
    1,
    'O jogo ensina programação: você escreve código que faz a fazenda trabalhar sozinha.',
  ),
  q(
    'q-search-5',
    'search',
    false,
    '"Shenzhen I/O" coloca o jogador para…',
    [
      'Cozinhar',
      'Dirigir carros',
      'Pintar casas',
      'Montar circuitos e programar microcontroladores',
    ],
    3,
    'No jogo você monta circuitos e programa os chips em uma linguagem parecida com Assembly.',
  ),
  q(
    'q-search-6',
    'search',
    false,
    'Aprender programação jogando é interessante porque…',
    [
      'Elimina a necessidade de estudar',
      'Não usa computador',
      'Dá para praticar lógica de forma divertida',
      'Só funciona no celular',
    ],
    2,
    'Jogos transformam a prática de lógica em desafio e diversão.',
  ),
  q(
    'q-search-7',
    'search',
    true,
    'O que esses jogos de programação ensinam, na prática?',
    [
      'A consertar hardware',
      'Raciocínio lógico e a ideia de instruções passo a passo',
      'A desenhar à mão',
      'A cantar',
    ],
    1,
    'Eles treinam lógica e a capacidade de dividir um problema em passos.',
  ),
  q(
    'q-search-8',
    'search',
    true,
    'Qual a principal diferença entre os dois jogos da apresentação?',
    [
      'O Farmer usa linguagem baseada em Python; o Shenzhen I/O usa um Assembly customizado',
      'Os dois usam PHP',
      'O Farmer usa Assembly e o Shenzhen usa Java',
      'Nenhum usa código',
    ],
    0,
    'Um parte do Python; o outro chega perto da máquina, com um Assembly customizado.',
  ),
  // O Jogo da Imitação
  q(
    'q-unit-test-4',
    'unit-test',
    false,
    'Em qual guerra se passa "O Jogo da Imitação"?',
    ['Segunda Guerra Mundial', 'Guerra do Paraguai', 'Guerra Fria', 'Primeira Guerra Mundial'],
    0,
    'O filme se passa na Segunda Guerra Mundial.',
  ),
  q(
    'q-unit-test-5',
    'unit-test',
    false,
    'Alan Turing é considerado um pioneiro de…',
    ['Pintura', 'Computação', 'Culinária', 'Esportes'],
    1,
    'Turing é um dos pais da computação.',
  ),
  q(
    'q-unit-test-6',
    'unit-test',
    false,
    'Como se chamava a máquina de códigos que Turing tentava decifrar?',
    ['Matrix', 'Eniac', 'Enigma', 'Tetris'],
    2,
    'A Enigma era a máquina de mensagens secretas.',
  ),
  q(
    'q-unit-test-7',
    'unit-test',
    true,
    'O que a história de Turing mostra sobre a computação?',
    [
      'Que lógica não importa',
      'Que máquinas e lógica podem ajudar a resolver problemas muito difíceis',
      'Que códigos não existem',
      'Que só humanos resolvem problemas',
    ],
    1,
    'Usar lógica e máquinas ajudou a resolver um problema que parecia impossível.',
  ),
  q(
    'q-unit-test-8',
    'unit-test',
    true,
    'Por que era inviável testar todas as combinações da Enigma "na mão" antes da meia-noite?',
    [
      'Porque a máquina não tinha senha',
      'Porque já estava decifrada',
      'Porque são combinações demais para uma pessoa testar a tempo',
      'Porque só funcionava em Python',
    ],
    2,
    'As combinações eram tantas que só um método inteligente (e uma máquina) daria conta.',
  ),
  // Estrelas Além do Tempo
  q(
    'q-breakpoint-4',
    'breakpoint',
    false,
    'Katherine Johnson trabalhava, no filme, com…',
    ['Moda', 'Jardinagem', 'Música', 'Cálculos de matemática para a NASA'],
    3,
    'Katherine calculava trajetórias para a NASA.',
  ),
  q(
    'q-breakpoint-5',
    'breakpoint',
    false,
    '"Estrelas Além do Tempo" se passa durante…',
    ['A Idade Média', 'A corrida espacial', 'A pré-história', 'A Revolução Industrial'],
    1,
    'O filme se passa na época da corrida espacial.',
  ),
  q(
    'q-breakpoint-6',
    'breakpoint',
    false,
    'O que as três protagonistas do filme tinham em comum?',
    [
      'Trabalharam na NASA e enfrentaram preconceito',
      'Eram atrizes de cinema',
      'Eram cantoras',
      'Eram jogadoras de vôlei',
    ],
    0,
    'As três trabalharam na NASA e superaram o preconceito com talento.',
  ),
  q(
    'q-breakpoint-7',
    'breakpoint',
    true,
    'Dorothy Vaughan ficou conhecida por aprender e ensinar…',
    ['Java', 'FORTRAN, linguagem dos computadores da época', 'PHP', 'HTML'],
    1,
    'Dorothy aprendeu FORTRAN e preparou a equipe para os computadores eletrônicos.',
  ),
  q(
    'q-breakpoint-8',
    'breakpoint',
    true,
    'O que o filme mostra sobre cálculos e computadores na NASA?',
    [
      'Que ninguém calculava nada',
      'Que só máquinas faziam contas',
      'Que pessoas fazendo contas à mão foram essenciais junto com os primeiros computadores',
      'Que a matemática era dispensável',
    ],
    2,
    'Os cálculos humanos foram decisivos, e as protagonistas ajudaram a entrar na era dos computadores.',
  ),
];

/** Pergunta do boss final: fixa na 1ª mão da THE INFINITE LOOP. Resume a apresentação. */
export const BOSS_QUESTION: Question = spread({
  id: 'q-boss-infinite-loop',
  card: 'while',
  topic: 'Fábrica de software',
  hard: true,
  prompt: 'THE INFINITE LOOP quer a sua resposta final: qual frase define melhor um software?',
  options: [
    'É a parte física do computador, como a tela e o teclado',
    'São programas e instruções que orientam o hardware a executar tarefas',
    'É qualquer coisa que se conecta à internet',
    'É só um tipo de jogo de computador',
  ],
  answer: 1,
  explanation:
    'Software é a parte lógica dos dispositivos: programas e instruções que orientam o hardware. É isso que a Fábrica de software constrói.',
});

export const ALL_QUESTIONS: readonly Question[] = [...QUESTIONS, BOSS_QUESTION];

const BY_ID = new Map(ALL_QUESTIONS.map((question) => [question.id, question]));

export function getQuestion(id: string): Question {
  const question = BY_ID.get(id);
  if (!question) throw new Error(`Pergunta desconhecida: ${id}`);
  return question;
}

export function hasQuestion(id: string): boolean {
  return BY_ID.has(id);
}

/**
 * Perguntas candidatas para a carta que lidera a mão. Mãos grandes puxam as difíceis; se não houver,
 * cai para qualquer pergunta da carta.
 */
export function questionPool(lead: CardId, big: boolean): Question[] {
  const all = QUESTIONS.filter((question) => question.card === lead);
  const level = all.filter((question) => question.hard === big);
  return level.length > 0 ? level : all;
}
